FROM node:latest as fe-build
WORKDIR /usr/archery/static/views
COPY archery-views .
RUN npm install 
RUN npm run build

FROM nginx:stable-alpine
COPY --from=fe-build /usr/archery/static/views/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 200
ENTRYPOINT [ "nginx","-g", "daemon off;" ]